### ISSUE TITLE
[v2] Feature request: renderPromise

### ISSUE THREAD

**Issue by zkat** [vadimdemedes/ink#125]
My use case for ink involves integrating it into a separate application that has its own exit handling and all that. In order to integrate ink, I need to have two things:

1. a way to exit from ink from within an ink component ("I've reached the final step, now please exit rendering")
2. a `renderPromise()` or similar method, instead of the current `render`, that resolves when the app unmounts.

I think that's it so far? Is this possible? I looked around and I'm not clear on how to do this but if you give me some guidance, I'm willing to put together a patch to support this soon, since it's a blocker for me using ink right now.

**Comment by vadimdemedes** [comment]
> 1. a way to exit from ink from within an ink component ("I've reached the final step, now please exit rendering")

Good idea, I think Ink could expose this via a new `AppContext` which would have `exit()` method and trigger unmounting of the whole app.

> 2. a `renderPromise()` or similar method, instead of the current `render`, that resolves when the app unmounts.

This is a reasonable feature request too, although this one's a bit trickier, ideally I would prefer to have only one render method. Trickier, because currently `render()` returns an `unmount()` function, so it would be a breaking change. Also, it seems that when `renderPromise()` would be used, there would be no way to `unmount()` manually from "outside".

What if `render()` returned a set of methods instead?

```js
const app = render()
await app.waitUntilExit() // renderAsPromise replacement
app.unmount()
```

**Comment by zkat** [comment]
This sounds great! The biggest blocker for me right now is the Ctrl+c handling, so that would need to be overridable too. Thanks for your response!

**Comment by vadimdemedes** [comment]
Ok, `2.0.0-13` is released!

How to unmount:

```jsx
const app = render(<App/>);
app.unmount();
```

How to wait until app finished executing:

```jsx
const app = render(<App/>);
await app.waitUntilExit();
```

How to exit from within the app:

```jsx
import {AppContext} from 'ink';

const App = ({onExit}) => (
	<JSX onSomeEvent={onExit}/>
)

const Wrapper = () => (
	<AppContext.Consumer>
		{({exit}) => (
			<App onExit={exit}/>
		)}
	</AppContext.Consumer>	
);
```

How to disable default Ctrl+C handling when in raw mode:

```jsx
render(<MyApp/>, {
	exitOnCtrlC: false
});
```

Thanks for the suggestions, @zkat!
