### ISSUE TITLE
Clearing old renders fails when the render goes beyond the vertical space available

### ISSUE THREAD

**Issue by joejag** [vadimdemedes/ink#158]
Hi, thank you very much for creating this project, I love the concept. 

I noticed a bug in my own program and noticed it's perhaps a problem with Ink itself. When the rendered view goes beyond the space available and the user scrolls back up to see the output, then older renders are still shown.

Here is an example using the Jest built-in example. I've tried this on Mac and Linux. The first run is where vertical space is not an issue and the second one shows the problem.

![example](https://user-images.githubusercontent.com/57625/54297700-458d6b00-45af-11e9-9f1e-3427411c5061.gif)

Notice old renders are still present.

Is this expected? Or is this something we could do something about?

**Comment by vadimdemedes** [comment]
Hi, thanks! :)

Unfortunately, this is expected behavior with terminals. Erasing lines doesn't work beyond what's visible in terminal's viewport. There's one workaround I know of - erasing all of terminal session, including previous output from all commands (all history). Jest is doing this, but I know they end up reducing frequency of renders because clearing all of history leads to flickering. I think Ink could detect that there are lines beyond terminal's viewport, then erase terminal and reduce frequency of renders by itself. Afterwards, if terminal's height increases, this mode could be turned back off and go back to normal rendering speed and behavior.

@SimenB Could you correct me if I'm wrong on Jest's behavior here? :)

**Comment by joejag** [comment]
Aha, yes, it seems this is a constraint with terminals.

Given the use case of my application, obliterating everything might be an option. Is there some code in Ink that I can use to achieve this?

Thanks.
Joe.

**Comment by vadimdemedes** [comment]
Not yet, but I'm considering including it perhaps as an opt-in behavior. I will keep you posted on this issue.

**Comment by vadimdemedes** [comment]
I'm going to keep it open for visibility, since other people may run into the same thing ;) Also, for myself to remember to implement that erase-all solution.

**Comment by vadimdemedes** [comment]
If anyone could test #210 with their apps, that'd be great!

**Comment by vadimdemedes** [comment]
Released in `2.5.0`, you can enable this feature via [experimental mode](https://github.com/vadimdemedes/ink#experimental-mode).

**Comment by LeeCheneler** [comment]
> Not yet, but I'm considering including it perhaps as an opt-in behavior. I will keep you posted on this issue.

Hey you mentioned potentially adding this as opt in behaviour @vadimdemedes but on the app we're developing now (very deep into its development) we've just come across this as a huge issue 😬 it doesn't seem to be opt in? Or are we missing something in the docs??

We're at the point right now where we're going to have to scrap the app and rebuild from scratch if we can't resolve this 😭 the entire terminal history gets wiped when the render is taller than the terminal 😳
