### ISSUE TITLE
Intercept calls to `stream.write`

### ISSUE THREAD

**Issue by SimenB** [vadimdemedes/ink#162]
Since `Ink` rerenders the whole screen, message printed using `process.stdout.write` will be gone. E.g. the message from node core when you attach more than 10 listeners to a single event.

It would be great if Ink could somehow intercept all calls to `stream.write` except for its own and somehow store them.

Spitballing here, but maybe add it to `StdoutContext` as an array or something? That way consumers can choose to have it as part of its output or not on its own.

If this is not something you want to do, it would be great of some separate `ink-stream` module could encapsulate this logic (and ink renders via a special `Symbol` or something so it can bypass the capture logic)

Related: `console.log` etc can also mess up, but I think that's outside the scope of this module

**Comment by vadimdemedes** [comment]
I think instead of storing out-of-Ink writes to `process.stdout`, Ink should handle that case instead and ensure those messages are written correctly to stdout. I was kind of hesitant to do it, because I had the same issue with Ink 1 and there's just no other way than to monkey-patch `process.stdout.write` 🤷‍♂️ Will fix it soon!

**Comment by mAAdhaTTah** [comment]
FWIW, `console.log` in Node uses [`stdout.write`](https://github.com/nodejs/node/blob/master/lib/internal/console/constructor.js#L239), so you might not need special handling for that.

**Comment by vadimdemedes** [comment]
So is Ink :) It also uses `stdout.write` via `log-update`, so we'll need some sort of way to figure out whether input is coming from Ink or not. I've started work on this using slightly modified https://yarnpkg.com/en/package/hook-std, will keep you posted. Feel free to also try it out yourself, if you want to ;)

**Comment by vadimdemedes** [comment]
Ink 3 is going to (re)introduce interception of `console.*` methods and it will display their output above Ink's output, so that there's no conflict between the two. Going to keep this issue open until Ink 3 is released.

It's not going to intercept calls to `stream.write` though. Back when I digged into it, all solutions seemed quite hacky, so I'm going to hold off on that one for now.

**Comment by mAAdhaTTah** [comment]
Can we get a mechanism for hooking into the intercepted messages & rendering them elsewhere if we want? There might be instances where one would prefer to collect the `console.log` messages and render them at the end.

**Comment by vadimdemedes** [comment]
I think it's out of scope of Ink, but I could add a setting to disable Ink's interception so you could add your own. Mind sharing what's the use case for this?

**Comment by mAAdhaTTah** [comment]
I'm building what is essentially a CRA clone with some additional tools integrated, one of which is Webpack. Some plugins emit console logs during build. I'd like those to not interrupt the spinner and instead display the logs from the build after it's completed, alongside the rest of the information about the run. It seems odd to have those logs emitted immediately rather than alongside the summary.

Capturing console messages feels like something you could opt into, either via a custom hook & custom component though, which would give you more control over what to do with them (including simply writing them out to stdout/stderr as you have currently).

**Comment by vadimdemedes** [comment]
Sounds good, I can add that setting to disable Ink's interception and release the interception code for console methods as a separate package, so you could reuse that.

**Comment by vadimdemedes** [comment]
Ink 3 is out with the fix for this issue included! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)
