### ISSUE TITLE
Throttle updates to N FPS (e.g. 60)?

### ISSUE THREAD

**Issue by KyleAMathews** [vadimdemedes/ink#212]
Given Ink has to update the entire screen — it might be nice to throttle updates globally to e.g. 60 FPS. We're seeing some issues in Gatsby like https://github.com/gatsbyjs/gatsby/issues/15505 that we can fix case by case but a global render throttle seems useful to explore.

**Comment by vadimdemedes** [comment]
Agree, would be a good improvement.

**Comment by vadimdemedes** [comment]
Released https://github.com/vadimdemedes/ink/releases/tag/v2.4.0, which throttles rendering to 60 FPS, if [experimental mode](https://github.com/vadimdemedes/ink#experimental-mode) is enabled. Thanks for suggestion! 

Will keep this issue open until new reconciler and renderer becomes a default one.

**Comment by eps1lon** [comment]
I gave it a try and it definitely helped (70s runtime instead of 240s). Though it's still faster to manually batch updates at 30fps (40s instead of 70s).

It would be perfect if we could set the fps ourselves. 60fps is too much IMO as a default. 60fps is needed for smooth animations and I'd say that most CLIs don't need smooth animations.

**Comment by vadimdemedes** [comment]
Yeah, good suggestion. I'll try lowering it to 30fps. I'm not sure ability to customize fps would be a good move, because it's more of avoiding the root cause of a problem, rather than properly fixing it. For example, a progress bar component might be implemented to refresh every 100ms, when 1s would be more than enough.

One thing I wanted to do for a while that could help performance a lot is avoiding rerendering layout when underlying React components didn't change (https://github.com/vadimdemedes/ink/issues/21).

**Comment by vadimdemedes** [comment]
Ink 3 is out! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)
