### ISSUE TITLE
Add `useFocus` hook to manage input focus

### ISSUE THREAD

**Issue by ukabu** [vadimdemedes/ink#242]
Do you have any recommandation for managing focus for multiple input component.
My current use case is to be able to display multiple SelectInput and be able to tab thru them. The component already have a focus prop, but how would I manage the focus when the multiple SelectInput are not within the same react component?

**Comment by sw-yx** [comment]
possibly related: https://github.com/jdeniau/ink-tab/issues/14

**Comment by vadimdemedes** [comment]
As you noted, you'd need to use `focus` prop, but I can see how that can become troublesome when components are elsewhere. Perhaps it's time to introduce something like `useFocus()` to make Ink manage focus and let 3rd-party components easily benefit from it. I will think about it more, but can't give you an ETA, so until then I'm afraid you'd have to implement a custom solution for this problem using a state for `focus` above your components, so that you can pass it down to multiple places.

**Comment by jdeniau** [comment]
I think it's a good approach that ink manage the focus, as does a web browser 👍

**Comment by jdeniau** [comment]
@vadimdemedes I started working on this here : https://github.com/jdeniau/ink-focus-demo 

There is still some work to do, things I don't really understand, and the external API is a little too complicated I think, but I think it is a good start to keep a global focus state if you are interested.

**Comment by jdeniau** [comment]
@vadimdemedes I have a working version on https://github.com/jdeniau/ink-focus-demo now.

The API is the following : 
Encapsulate every component that may be focusable like that : 
```js
import TextInputWithoutFocus from "ink-text-input";
import { withFocus } from "ink";

const TextInput = withFocus(TextInputWithoutFocus);
```
_[See TextInput.js](https://github.com/jdeniau/ink-focus-demo/blob/master/src/TextInput.js)_

The wrapped component will receive a `focus` boolean prop (I used the `ink-text-input` props, but I think `isFocused` or `hasFocus` is more clear).

Ink should then manage focus between every focusable elements. _[App.js](https://github.com/jdeniau/ink-focus-demo/blob/master/src/App.js)_

You can switch between focusable elements by pressing "tab" or "shift+tab"

There is one "problem" I still see before making a PR : 
I don't see a way to make the wrapped component unresponsive to keyboard input. That's why we need the `focus` prop, but there still is a conflict with the "tab" key : 
As every component registers itself on either "keypress" or "data" listener, there is a weird issue when you switch between two inputs : one of them (the "focused" one) will receive a "tab" input.
It can be easily managed (and required) in every library that use `withFocus` but it's sad that there are no other options here.

**Comment by vadimdemedes** [comment]
I have had only rough ideas for `useFocus`, so I'm very curious to check out your take on it, nice!

**Comment by vadimdemedes** [comment]
I checked out your repo and it's really good, very similar to what I had in mind. The only difference would be that I'd prefer users to use `useFocus` hook directly instead of `withFocus` HOC.

>  don't see a way to make the wrapped component unresponsive to keyboard input. That's why we need the focus prop, but there still is a conflict with the "tab" key

Good point, not sure what's the ideal solution here. One way to solve this would be to let text inputs that expect "Tab" to disable focus switching? It's not perfect, but I don't think majority of text inputs would expects those.

**Comment by jdeniau** [comment]
Thanks!

I think it will do the trick.
I haven't stop thinking about this, and I think the ideal solution would be
to implement the same pattern as the browser do and thus I'm not fully
satisfied withmy implementation.
As I don't want to push code that might imply a breaking change soon, I
preferred keep thinking about it.


Le dim. 16 févr. 2020 à 13:02, Vadim Demedes <notifications@github.com> a
écrit :

**Comment by jdeniau** [comment]
As I re-read my code about that, I think we might expose both `useFocus` and `withFocus`, but `useFocus` is a little harder here, as you need to provide a `ref` to your component (but you will have more control afterwards).

Another way around is to return a ref that you might inject in your component this way:
```js
function FooInput() {
  const [hasFocus, ref] = useFocus(possibleRef);
}
```
but that seems really really weird 🙃

**Comment by jdeniau** [comment]
I managed to remove the `ref` dependency, I will need to test it further.

As soon as I manage to handle the `TAB` key, I will open a PR

**Comment by charlex** [comment]
This would be really awesome. I feel right now I have to reinvent the wheel here to do this.

**Comment by vadimdemedes** [comment]
Ink 3 is out! Read the full announcement at https://vadimdemedes.com/posts/ink-3 :)
