### ISSUE TITLE
Global option to disable all colored output

### ISSUE THREAD

**Issue by colinking** [vadimdemedes/ink#248]
What do you think of adding an option, maybe passed to `render`, that disables all colored output?

This could just be a flag that changes the behavior of the `Color` component that toggles whether this `transformChildren` method is provided or not: https://github.com/vadimdemedes/ink/blob/e0d2b4fcad9860b275f5149c4a4a893c8810026c/src/components/Color.js#L41

The use-case is that some terminals may have limited color support, say f.e. rendering `grey` text with the same color as the terminal background. An easy solution for these users would be to offer a flag that disables colored output.

**Comment by sindresorhus** [comment]
> The use-case is that some terminals may have limited color support, say f.e. rendering grey text with the same color as the terminal background.

What terminals? That sounds like a bug that should be reported to such terminals.

**Comment by colinking** [comment]
This was reported specifically with the default Ubuntu terminal, and I've since recreated it with some example images in the upstream issue here: https://github.com/segmentio/typewriter/issues/115

This might be how 8-color terminals render this kind of text, but I haven't gotten around to digging in quite yet :)

**Comment by sindresorhus** [comment]
You can already do `$ some-cli --no-color` as Chalk (the coloring library) [respects that flag](https://github.com/chalk/chalk#chalksupportscolor).

I would also consider trying to work around the issue in Chalk or Ink instead of putting that burden on every Ink consumer. Maybe we can detect that Ubuntu terminal and just do white instead of gray then.

It would be good to figure out exactly what terminal, version, Ubuntu version, etc, and get it reported upstream.
