### ISSUE TITLE
Embed a terminal within an Ink application

### ISSUE THREAD

**Issue by KyleAMathews** [vadimdemedes/ink#272]
Is this possible some how?

**Comment by vadimdemedes** [comment]
You could try spawning `bash` and piping input/output to/from this process. I think it's going to be very challenging to support something like this, because you can't know which programs will be executed in that terminal session and what is their output like, because it could mess up output of your (parent) CLI.

**Comment by KyleAMathews** [comment]
Ah yeah good point. It'd be hard I assume to filter things correctly 👍
