### ISSUE TITLE
Render cursor

### ISSUE THREAD

**Issue by mnewt** [vadimdemedes/ink#47]
Really awesome project. Thanks for building it.

I want to make a normal readline-style prompt, complete with the standard cursor. I see ink-text-input but it doesn't render the cursor. Can you point me in the right direction?

Cheers.

**Comment by vadimdemedes** [comment]
Thanks, glad you like it! It's definitely the priority on the roadmap, but it involves quite a lot of time to implement properly. I won't give any ETAs here, but I'll keep you updated.

**Comment by vadimdemedes** [comment]
Closing it, as it turned out to be really complex to move a native cursor to the correct position. Instead, it's much easier to fake the cursor like https://github.com/vadimdemedes/ink-text-input does it. Feel free to check out the source on how it's done. Basically it's storing fake cursor's position and highlighting the character on that position with `chalk.inverse()`.
